[tool.poetry]
name = "text2code"
version = "0.1.0"
description = ""
authors = ["Owais Multani <owais@quantive.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
