# Generated by Django 5.0.4 on 2024-04-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_chat_id_alter_chat_title_alter_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='code',
            field=models.CharField(default='', max_length=1000000),
        ),
    ]
