# Generated by Django 5.0.4 on 2024-04-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chat_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='suggested_language',
            field=models.CharField(default='', max_length=255),
        ),
    ]
