# Generated by Django 5.0.4 on 2024-04-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chat_suggested_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='role',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
