import openai
import json

class CodeGenerator:
    def __init__(self, api_key, model="gpt-3.5-turbo", temperature=0.5, max_tokens=150):
        """
        Initialize the code generator with necessary parameters.

        Parameters
        ----------
        api_key : str
            Your OpenAI API key.
        model : str, optional
            The model to use for code generation. Default is 'gpt-3.5-turbo'.
        temperature : float, optional
            Controls randomness in the output. Lower values mean less random outputs.
            Default is 0.5.
        max_tokens : int, optional
            The maximum number of tokens to generate in the output. Default is 150.

        """
        self.api_key = api_key
        self.model = model
        self.temperature = temperature
        self.max_tokens = max_tokens
        openai.api_key = self.api_key

    def generate_code(self, chat) -> dict:
        """
        Generate code based on the given messages using OpenAI's API.

        Parameters
        ----------
        chat : Chat
            The chat instance.

        Returns
        -------
        dict
            A dictionary containing the generated message, code, and language.
        """
        messages = chat.messages.all()
        client = openai.Client(api_key=self.api_key)
        response = client.chat.completions.create(
            model=self.model,
            messages=self._create_messages(messages),
            functions=self.__get_text2code_func_conf(),
            function_call = 'auto'
        )
        message = response.choices[0].message
        if message.function_call is not None:
            parsed_response = self.parse_function_call_response(message)
        else:
            parsed_response = self.parse_content_response(message)

        return parsed_response


    @staticmethod
    def parse_function_call_response(message):
        """Extract data from function call response."""
        json_response = json.loads(message.function_call.arguments)
        return {
            'message': json_response.get('message', ''),
            'code': json_response.get('code', ''),
            'language': json_response.get('language', '')
        }
    
    @staticmethod
    def parse_content_response(message):
        """Extract data from content response."""
        args = message.content.split('```')
        if len(args) == 1:
            return {'message': args[0], 'code': '', 'language': ''}
        
        language, code = args[1].split('\n', 1)
        message = args[0] + args[2]
        return {'message': message, 'code': code, 'language': language}

    @staticmethod
    def _create_messages(messages):
        """
        Create a list of messages in the format required by OpenAI's API.

        Parameters
        ----------
        messages : list
            List of messages to generate code from.

        Returns
        -------
        list
            List of messages in the required format.
        """
        messages = [
            {"role": "assistant", "content": message.text} if message.role == 'assistant' else {"role": "user", "content": message.text}
            for message in messages
        ]
        return messages
    
    @staticmethod
    def __get_text2code_func_conf():
        """
        Get the json representation of the text2code function.
        """
        text2code_func = [
            {
                'name': 'convert_text_to_code',
                'description': 'Convert text to code from the messages',
                'parameters': {
                    'type': 'object',
                    'properties': {
                        'message': {
                            'type': 'string',
                            'description': 'The output message from the chatbot eg. "I have generated the code for you"'
                        },
                        'code': {
                            'type': 'string',
                            'description': 'The code generated by the chatbot. eg. "print(\'Hello, World!\')"'
                        },
                        'language': {
                            'type': 'string',
                            'description': 'The programming language used for the generated code. eg. "python"'
                        }
                    }
                },
                'required': ['message', 'code', 'language'],
            }
        ]
        return text2code_func